version: 2

build:
  os: "ubuntu-22.04"
  image: "latest"
  tools:
    python: "3.12.3"
  commands:
    - sphinx-build -b html backend/docs/source backend/docs/build/html

formats:
  - htmlzip

# Skip automatic documentation build
sphinx:
  configuration: "backend/docs/source/conf.py"
  builder: ""

python:
  install:
    - method: pip
    - requirements: backend/requirements.txt
