version: 2

build:
  image: "latest"
  python: "3.12.3"

formats:
  - htmlzip

# Skip automatic documentation build
sphinx:
  configuration: "backend/docs/source/conf.py"
  builder: ""

python:
  install:
    - method: pip
    - requirements: backend/requirements.txt
