version: 2

build:
  os: "ubuntu-22.04"
  image: "latest"
  tools:
    python: "3.12"
  commands:
    - sphinx-build -b html backend/docs/source backend/docs/build/html
    
formats:
  - htmlzip

sphinx:
  configuration: "backend/docs/source/conf.py"

python:
  install:
    - requirements: backend/requirements.txt
